# Chunk size experiments
CHUNK_SIZE = 300
CHUNK_OVERLAP = 50

CHUNK_SIZE_SMALL = 150
CHUNK_OVERLAP_SMALL = 25

CHUNK_SIZE_LARGE = 600
CHUNK_OVERLAP_LARGE = 100

# Reranker config
RERANKER_CANDIDATE_K = 20
RERANKER_TOP_N = 5
